# Generated by Django 2.0.2 on 2018-02-05 16:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=100)),
                ('userphoto', models.ImageField(null=True, upload_to='static/hackathon/userimages', validators=[django.core.validators.FileExtensionValidator(['jpeg', 'png', 'bmp', 'jpg'], 'file exteion not valid')])),
                ('first', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
